### ISSUE TITLE
Rust compiler integration

### ISSUE THREAD

**Issue by aleasims** [NilFoundation/zkllvm-circifier#10]
This is a complex issue, covering many steps. Certain tasks should be created in a separate issue (mostly in referred repo).

Integrate Rust compiler (https://github.com/nilfoundation/zkllvm-rslang) with circifier LLVM:

* New Rust frontend, supporting required constructions (as circifiers clang frontend does)
* New LLVM IR support
* and etc.

**Comment by aleasims** [comment]
Because rslang is no longer a part of circifier, probably should consider closing this issue or move it to more suitable place. Probably it can be an epic issue in zkLLVM repo.

**Comment by karakazyablek** [comment]
@aleasims definitely it will be great to have one epic ticket for the whole rust compiler. Also it will be super helpful, if we add some related ticket in this epic to understand what we have already done and what need to be done in the future. Could you add some related tickets to this epic?
